export const editedGame = {
/*
    'a8': 'black_rook',
    'b8': 'black_knight',
    'c8': 'black_bishop',
    'd8': 'black_queen',
    'd6': 'black_king',
    'f8': 'black_bishop',
    'g8': 'black_knight',
    'h8': 'black_rook',
    'a7': 'black_pawn',
    'b7': 'black_pawn',
    'c7': 'black_pawn',
    'd5': 'black_pawn',
    'e7': 'black_pawn',
    'f7': 'black_pawn',
    'g7': 'black_pawn',
    'h7': 'black_pawn',
    
    'a1': 'white_rook',
    'b1': 'white_knight',
    'c1': 'white_bishop',
    'd1': 'white_queen',
    'e1': 'white_king',
    'f1': 'white_bishop',
    'g1': 'white_knight',
    'h1': 'white_rook',
    'a2': 'white_pawn',
    'b2': 'white_pawn',
    'c2': 'white_pawn',
    'd2': 'white_pawn',
    'e4': 'white_pawn',
    'f4': 'white_pawn',
    'g5': 'white_pawn',
    'h2': 'white_pawn',
 */   
    'a1': 'white_rook',
    'e8': 'black_king',
    'f3': 'white_rook',
    'd3': 'white_queen',
    'c8': 'black_rook',
    'b3': 'white_rook',
    'g6': 'white_rook',
    'h5': 'white_bishop',

};